<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/10/23
 * Time: 18:11
 */
namespace app\web\controller;
use app\common\Home;

class Article extends Home{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \think\response\View
     * @throws \think\exception\DbException
     */
    public function index(){
        $data=model('Article')
            ->where(['acid'=>$this->acid,'is_delete'=>0,'genre'=>1])
            ->order('id desc')
            ->paginate('',false,['query'=>$_GET]);
        foreach ($data as $key=>$val){
            $data[$key]['content']=strip($val['content'],30);
        }
        return view('',['data'=>$data]);
    }
    public function clause(){
        $data=[
            ['title'=>'下单说明','genre'=>2],['title'=>'用户协议','genre'=>3]
        ];
        return view('',['data'=>$data]);
    }
    public function clause_edit($genre){
        $data=model('Article')
            ->where(['genre'=>$genre,'acid'=>$this->acid])
            ->order('id desc')
            ->find();
        if(empty($data)){
            $title=[2=>'下单说明',3=>'用户协议'];
            $data=[
                'title'=>$title[$genre],
                'content'=>'',
                'genre'=>$genre
            ];
        }
        return view('',['data'=>$data]);
    }
    public function edit($id, $data = [], $rule = '')
    {
        return parent::edit($id, $data, $rule); // TODO: Change the autogenerated stub
    }

    public function add(){
        if(request()->isPost()){
           $data=[
               'title'=>input('title',''),
               'content'=>input('content',''),
               'genre'=>input('genre',1),
               'acid'=>$this->acid,
               'sort'=>input('sort',1)
           ];
           $genre=[2=>'下单说明',3=>'用户协议'];
           if(isset($genre[$data['genre']]))$data['title']=$genre[$data['genre']];
           $res=model('Article')->validate([['title','require|min:3','标题不能为空|标题名称不能小于三个字符']])->save($data);
           if(empty($res))return json(['code'=>1,'msg'=>model('Article')->getError()]);
           if($data['genre']==1){
               return json(['code'=>0,'msg'=>'添加成功','url'=>we7_url('article/index')]);
           }else{
               return json(['code'=>0,'msg'=>'修改成功','url'=>we7_url('article/clause')]);
           }
        }
        return view();
    }
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}