<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/10/24
 * Time: 10:50
 */
namespace app\web\controller;
use app\common\Home;

class Classify extends Home{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $parent_id
     * @return \think\response\View
     */
    public function index($parent_id=0){
        $data=model('Classify')
            ->where(['is_delete'=>0,'acid'=>$this->acid])
            ->where(['parent_id'=>$parent_id])
            ->order('id desc')
            ->paginate('',false,['query'=>$_GET]);
        if($parent_id==0){
            return view('',['data'=>$data]);
        }else{
            return view('seed',['data'=>$data]);
        }
    }

    /**
     * @return \think\response\View
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function add(){
        if(request()->isPost()){
            $data=[
                'title'=>input('title'),
                'parent_id'=>input('parent_id',0),
                'logo'=>input('image_url'),
                'abstract'=>input('abstract'),
                'content'=>input('content'),
                'price'=>input('price'),
                'acid'=>$this->acid,
                'sort'=>input('sort',1)
            ];
            $res=model('Classify')
                ->validate([
                    ['title','require|min:2|max:50','标题错误|标题不能小于2个字|标题不能大于50个字'],
                    ['logo','require','请上传图片'],
                    ['abstract','max:20','说明不能大于20个字'],
                ])->save($data);
            if(empty($res))return json(['code'=>1,'msg'=>model('Classify')->getError()]);
            return json(['code'=>0,'msg'=>'添加成功','url'=>we7_url('Classify/index')]);
        }else{
            $class=model('Classify')
                ->where(['is_delete'=>0,'acid'=>$this->acid,'parent_id'=>0])
                ->select();
            return view('',['class'=>$class]);
        }
    }
    public function delete($id)
    {
       $res=model('Classify')
           ->where(['is_delete'=>0,'acid'=>$this->acid])
           ->find();
       if(empty($res))return json(['code'=>1,'msg'=>'删除的内容不存在']);
       if($res->parent_id==0){
           $where=['parent_id|id'=>['eq',$res->id],'acid'=>$this->acid];
       }else{
           $where=['id'=>$res->id,'acid'=>$this->acid];
       }
        $res=model('Classify')
            ->save(['is_delete'=>1],$where);
       if(empty($res))return json(['code'=>1,'msg'=>'删除失败']);
       return json(['code'=>0,'msg'=>'删除成功']);
    }
    public function edit($id, $data = [],$rule='')
    {
        $data=[
            'title'=>input('title'),
            'parent_id'=>input('parent_id',0),
            'logo'=>input('image_url'),
            'abstract'=>input('abstract'),
            'content'=>input('content'),
            'price'=>input('price'),
            'acid'=>$this->acid,
            'sort'=>input('sort',1)
        ];
        $rule=[
            ['title','require|min:2|max:50','标题错误|标题不能小于2个字|标题不能大于50个字'],
            ['logo','require','请上传图片'],
            ['abstract','max:20','说明不能大于20个字']];
        return parent::edit($id, $data,$rule); // TODO: Change the autogenerated stub
    }
}