<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/10/30
 * Time: 12:52
 */
namespace app\web\controller;
use app\common\Home;
use think\Db;
class SmsSetting extends Home{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \think\response\View
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function index(){
        if(request()->isPost()){
            $data=[
                'access_key_id'=>input('access_key_id'),
                'access_key_secret'=>input('access_key_secret'),
                'sign'=>input('sign'),
                'variable'=>input('variable'),
                'tpl_id'=>input('tpl_id'),
                'acid'=>$this->acid
            ];
            $res=Db::name('SmsSetting')
                ->insert($data);
            if($res)return json(['code'=>0,'msg'=>'保存成功']);
            return json(['code'=>1,'msg'=>'保存失败']);
        }
        $data=Db::name('SmsSetting')
            ->where(['acid'=>$this->acid])
            ->order('id desc')
            ->find();
        !$data&&$data=[
            'access_key_id'=>'',
            'access_key_secret'=>'',
            'sign'=>'',
            'variable'=>'',
            'tpl_id'=>''
        ];

        return view('',['data'=>$data]);
    }
}