<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/11/15
 * Time: 10:35
 */
namespace app\web\controller;
use app\common\Home;
use app\common\model\User as ModelUser;
use app\common\model\Address;
class User extends Home{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户列表
     * @param string $search
     * @return \think\response\View
     * @throws \think\exception\DbException
     */
    public function index($search=''){
        $where=[];
        $search&&$where['nickname|id|mobile']=['like',"%{$search}%"];
        $data=ModelUser::where(['acid'=>$this->acid])
            ->order('create_time desc')
            ->where($where)
            ->paginate('',false,['query'=>$_GET]);

        return view('',['data'=>$data]);
    }

    /**
     * 收货地址管理
     * @param string $search
     * @return \think\response\View
     * @throws \think\exception\DbException
     */
    public function address($search=''){
        $where=[];
        $search&&$where['u.nickname|a.username|a.id|a.mobile|a.address']=['like',"%{$search}%"];
        $data=Address::alias('a')
            ->join('User u','u.id=a.uid')
            ->where(['a.acid'=>$this->acid,'a.is_delete'=>0])
            ->where($where)
            ->order('a.create_time')
            ->field('u.nickname,u.avatar_url,a.*')
            ->paginate('',false,['query'=>$_GET]);
        return view('',['data'=>$data]);
    }
}