<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/10/23
 * Time: 9:12
 */
namespace app\common;

use app\common\model\Order;

class Home extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('account',$this->We7->account);
        $this->assign('we7_name',$this->We7->username);
    }

    /**
     * @param $id
     * @param array $data
     * @param string $rule
     * @return \think\response\Json|\think\response\View
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * 详情和修改
     */
    protected function edit($id,$data=[],$rule=''){
        $controller=request()->controller();
        $find=model($controller)
            ->where(['id'=>$id,'acid'=>$this->acid,'is_delete'=>0])
            ->find();
        if(request()->isPost()){
            if(!count($data)){
                $data=input('post.');
            }

            $res=model($controller)->validate($rule)->save($data,['acid'=>$this->acid,'id'=>$id]);
            if(empty($res))return json(['code'=>1,'msg'=>model($controller)->getError()]);
//            $url=we7_url(request()->controller()."/index");
            return json(['code'=>0,'msg'=>'修改成功']);
        }else{
            if(empty($find))error_back('修改的内容不存在');
            return view('',['data'=>$find]);
        }
    }

    /**
     * 删除
     * @param $id
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function delete($id){
        if(request()->isPost()){
            $controller=request()->controller();
            $find=model($controller)
                ->where(['id'=>$id,'acid'=>$this->acid])
                ->find();
            if(empty($find))return json(['code'=>1,'msg'=>'删除的内容不存在']);
            if(isset($find->is_delete)){
                $res=model($controller)->save(['is_delete'=>1],['id'=>$find->id]);
            }else{
                $res=model($controller)->where(['id'=>$find->id])->delete();
            }
            if(empty($res))return json(['code'=>1,'msg'=>'删除失败']);
            return json(['code'=>0,'msg'=>'删除成功']);
        }
        return json(['code'=>1,'msg'=>'非法操作']);
    }


}