<?php
/**
 * Created by PhpStorm.
 * User: Yeah
 * Date: 2018/11/8
 * Time: 15:17
 */
namespace app\api\controller;
use app\common\Api;

class Article extends Api{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $genre
     * @param string $id
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function details($genre=1,$id=''){
        $where=['genre'=>$genre,'acid'=>$this->acid];
        $id&&$where['id']=$id;
        $data=model('Article')
            ->where($where)
            ->order('id desc')
            ->find();
        if(empty($data)&&!$id){
            $title=[2=>'下单说明',3=>'用户协议'];
            $data=[
                'title'=>$title[$genre],
                'content'=>'',
                'genre'=>$genre
            ];
        }
        return json(['code'=>0,'msg'=>'获取成功','data'=>$data]);
    }
}